[package]
name = "sisyphus"
version = "0.1.0"
edition = "2024"

[dependencies]
arrayvec = "0.7"
clap = { version = "4", features = ["derive"] }
rand = "0.8"
rand_chacha = "0.3"

[profile.dev]
opt-level = 1
